name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Run Selenium tests
        run: mvn test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports

  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚨 GitHub Actions CI Failed!"
          body: "The CI pipeline failed. Check logs here: https://github.com/lady-emily/CI-Pipeline_GitHubActions_Selenium/actions"
          to: "your-email@example.com"
          from: "GitHub Actions Bot"

      - name: Send Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "🚨 GitHub Actions CI Failed! Check logs: https://github.com/lady-emily/CI-Pipeline_GitHubActions_Selenium/actions"
