name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Install Chrome for Selenium
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Verify Chrome Installation
        run: google-chrome --version

      - name: Build and Run Tests
        run: mvn clean test

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports/

#  notify:
#    needs: test
#    runs-on: ubuntu-latest
#    if: always()
#
#    steps:
#      - name: Send Slack Notification
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
#          SLACK_MESSAGE: "GitHub Actions CI Pipeline completed with status: ${{ job.status }}"
#          SLACK_TITLE: "CI Pipeline Status"
#          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
#
#      - name: Send Email Notification
#        uses: dawidd6/action-send-mail@v3
#        with:
#          server_address: smtp.gmail.com
#          server_port: 587
#          username: ${{ secrets.EMAIL_USERNAME }}
#          password: ${{ secrets.EMAIL_PASSWORD }}
#          subject: "GitHub Actions CI Pipeline Status"
#          to: "ladyquarshie25@gmail.com"
#          from: "GitHub Actions"
#          body: |
#            CI Pipeline has completed.
#            Status: ${{ job.status }}
#          content_type: text/plain
